In [1]:
import pandas as pd
import numpy as np

In [2]:
df_inside = pd.read_csv('Dataset3_temp/data_inside.csv')

In [3]:
df_inside['time'] = pd.to_datetime(df_inside['time'])

In [7]:
df_inside['command_binary'] = np.where(df_inside['command'] == 'on', 1, 0)

In [8]:
df_inside

,time,temperature,humidity,pressure,current,voltage,command,command_binary
0,2023-05-16 11:09:21.673933,3.468571,23.093810,101965.833333,65401.45,18501.12,Setup,0
1,2023-05-16 11:10:11.218381,3.393333,22.996667,101963.792381,65401.45,18501.12,on,1
2,2023-05-16 11:10:59.754855,3.327143,22.934286,101964.977143,65401.45,18501.12,on,1
3,2023-05-16 11:11:48.302670,3.260476,22.865238,101968.345714,65401.45,18501.12,on,1
4,2023-05-16 11:12:36.846893,3.202857,22.820000,101968.622381,65401.45,18501.12,on,1
...,...,...,...,...,...,...,...,...
171,2023-05-16 13:27:47.262177,-0.030952,23.126190,101981.346190,65401.45,18501.12,off,0
172,2023-05-16 13:28:35.813647,-0.036667,23.248095,101978.092857,65401.45,18501.12,off,0
173,2023-05-16 13:29:24.365108,-0.033333,23.521429,101977.351429,65401.45,18501.12,off,0
174,2023-05-16 13:30:12.916643,-0.034286,23.915714,101979.116190,65401.45,18501.12,off,0
175,2023-05-16 13:31:01.468062,-0.018571,24.456667,101979.696190,65401.45,18501.12,off,0